version: "3.9"
services:
  desktop:
    build: ./Desktop
  mobile:
    build: ./Mobile
  nginx:
    build: ./Nginx
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8000:8000
