version: "3.9"
services:
  desktop:
    build: ./Desktop
  mobile:
    build: ./Mobile
  nginx:
    build: ./Nginx
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - "./Assets:/etc/nginx/Assets"
      - "./Mobile/public/mstatic:/etc/nginx/mstatic"
      - "./Desktop/public/dstatic:/etc/nginx/dstatic"
    ports:
      - 8000:8000
